name: Make lists

on:
  schedule:
    - cron: '22 2 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    branches: [ master ]
  label:
    branches: [ master ]
  
  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gover: ["1.1","1.2","1.3","1.4","1.5","1.6","1.7","1.8","1.9","1.10","1.11","1.12","1.13","1.14","1.15","1.16","1.17"]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.17"

    - name: Make list
      run: |
        go install golang.org/dl/go1.${{ matrix.gover }}@latest
        go1.${{ matrix.gover }} tool dist list > go-tool-dist-list.1.${{ matrix.gover }}.txt
      
    - uses: actions/upload-artifact@v2
      with:
        name: "go-tool-dist-list.1.${{ matrix.gover }}.txt"
        path: "go-tool-dist-list.1.${{ matrix.gover }}.txt"
    
  export:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Init
      run: mkdir release
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
      # Destination path
          path: "release/"
    
    - name: Prepare Release Variables
      id: vars
      uses: tendermint/starport/actions/release/vars@develop
      
    - name: Delete the "latest" Release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      if: ${{ steps.vars.outputs.is_release_type_latest == 'true' }}
      with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          delete_release: true

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish the Release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          files: release/*
          prerelease: true 
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
