name: Make lists

on:
  schedule:
    - cron: '22 2 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    branches: [ master ]
  label:
    branches: [ master ]
  
  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gover: ["go1.1","go1.2","go1.3","go1.4","go1.5","go1.6","go1.7","go1.8","go1.9","go1.10","go1.11","go1.12","go1.13","go1.14","go1.15","go1.16","go1.17"]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.node }}

    - name: Make list
      run: go tool dist list >> go-tool-dist-list.${{ matrix.node }}.txt
      
    - uses: actions/upload-artifact@v2
      with:
        name: go-tool-dist-list.${{ matrix.node }}.txt
        path: go-tool-dist-list.${{ matrix.node }}.txt
    
  export:
    runs-on: ubuntu-latest
    steps:
    - name: Init
      run: mkdir release
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
      # Destination path
          path: "release/"
    
    - name: Prepare Release Variables
      id: vars
      uses: tendermint/starport/actions/release/vars@develop
      
    - name: Delete the "latest" Release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      if: ${{ steps.vars.outputs.is_release_type_latest == 'true' }}
      with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          delete_release: true

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish the Release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          files: release/*
          prerelease: true 
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
